[build]
# The index HTML file to drive the bundling process.
target = "crates/odyexp-desktop/index.html"
# The output dir for all final assets.
dist = "trunk_dist"
# The public URL from which assets are to be served.
public_url = "/"


[watch]
watch = ["crates/odyexp-viewer/src", "crates/odyexp-desktop/assets", "crates/odyexp-io/src"]

